
JADE?=openjade
#JADE_XML_DCL?=/usr/local/share/sgml/docbook/dsssl/modular/dtds/decls/xml.dcl
JADE_XML_DCL?=/usr/share/sgml/docbook/dsssl-stylesheets-1.78/dtds/decls/xml.dcl
#JADE_CATALOG?=/usr/local/share/sgml/catalog
JADE_CATALOG?=/usr/share/sgml/CATALOG.db42xml:/usr/share/sgml/CATALOG.openjade:/usr/share/sgml/CATALOG.docbkdsl:/usr/share/sgml/CATALOG.iso_ent
