package com.foo_baz.v_q.ivqPackage;


/**
* com/foo_baz/v_q/ivqPackage/domain_info.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from /home/new/SuSe/users/svn/codes/ihs/trunk/src/vq.idl
* niedziela, 20 listopad 2005 22:12:57 CET
*/


/// domains
public final class domain_info implements org.omg.CORBA.portable.IDLEntity
{
  public int id_domain = (int)0;
  public String domain = null;

  public domain_info ()
  {
  } // ctor

  public domain_info (int _id_domain, String _domain)
  {
    id_domain = _id_domain;
    domain = _domain;
  } // ctor

} // class domain_info
