package com.foo_baz.v_q.ivqPackage;


/**
* com/foo_baz/v_q/ivqPackage/domain_info.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /export/home/new/svn/berlios.de/ihs/trunk/vq.idl
* sobota, 24 grudzieñ 2005 13:57:44 CET
*/

public final class domain_info implements org.omg.CORBA.portable.IDLEntity
{
  public int id_domain = (int)0;
  public String domain = null;

  public domain_info ()
  {
  } // ctor

  public domain_info (int _id_domain, String _domain)
  {
    id_domain = _id_domain;
    domain = _domain;
  } // ctor

} // class domain_info
