package com.foo_baz.v_q;


/**
* com/foo_baz/v_q/except.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from /home/new/SuSe/users/svn/codes/ihs/trunk/src/vq.idl
* wtorek, 15 listopad 2005 00:04:07 CET
*/

public final class except extends org.omg.CORBA.UserException
{
  public String what = null;
  public String file = null;
  public int line = (int)0;

  public except ()
  {
    super(exceptHelper.id());
  } // ctor

  public except (String _what, String _file, int _line)
  {
    super(exceptHelper.id());
    what = _what;
    file = _file;
    line = _line;
  } // ctor


  public except (String $reason, String _what, String _file, int _line)
  {
    super(exceptHelper.id() + "  " + $reason);
    what = _what;
    file = _file;
    line = _line;
  } // ctor

} // class except
